import React from "react";
import { Geist, Geist_Mono, Space_Mono } from "next/font/google";
import "./globals.css";
import { Navigation } from "@/components/Navigation";
import { ScrollProgress } from "@/components/magicui/scroll-progress";
import { AuroraBg } from "@/components/AuroraBg";
import { ThemeProvider } from "@/context/ThemeContext";

const spaceMono = Space_Mono({
  variable: "--font-space-mono",
  weight: "400",
  subsets: ["latin"],
  display: "swap"
})
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Naresh Choudhary",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${spaceMono.variable} ${geistSans.variable} ${geistMono.variable} antialiased dark`}>
        <ThemeProvider>
          <ScrollProgress />
          <AuroraBg />
          <div className="relative w-full md:w-[1000px] mx-auto">
            {children}
            <Navigation />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
